export const EVENTS = {
    ORDER_CONFIRMED: "ORDER_CONFIRMED",
    ORDER_PROCESSED: "ORDER_PROCESSED",
    ORDER_SHIPPED: "ORDER_SHIPPED",
    ORDER_OUT_FOR_DELIVERY: "ORDER_OUT_FOR_DELIVERY",
    ORDER_DELIVERED: "ORDER_DELIVERED",

    RETURN_REQUEST_APPROVED: "RETURN_REQUEST_APPROVED",
    RETURN_PICKUP_SCHEDULED: "RETURN_PICKUP_SCHEDULED",
    RETURN_RECEIVED: "RETURN_RECEIVED",
    REFUND_INITIATED: "REFUND_INITIATED",
    REFUND_COMPLETED: "REFUND_COMPLETED",

    RETURN_STATUS_UPDATED: "RETURN_STATUS_UPDATED",

    SUPPORT_TICKET_CREATED: "SUPPORT_TICKET_CREATED",
    SUPPORT_AGENT_REPLIED: "SUPPORT_AGENT_REPLIED",
    SUPPORT_TICKET_RESOLVED: "SUPPORT_TICKET_RESOLVED",

    CART_ABANDONED_1H: "CART_ABANDONED_1H",
    CART_ABANDONED_24H: "CART_ABANDONED_24H",
    PRICE_DROP_WISHLIST: "PRICE_DROP_WISHLIST",

    REVIEW_REQUEST: "REVIEW_REQUEST"
};

export const NOTIFICATION_CATEGORIES = {
    ORDER: "ORDER",
    SUPPORT: "SUPPORT",
    MARKETING: "MARKETING",
    SYSTEM: "SYSTEM"
};
