export const SELLER_CREATED = "SELLER_CREATED";
export const SELLER_UPDATED = "SELLER_UPDATED";
export const SELLER_DELETED = "SELLER_DELETED";

export const INVENTORY_CREATED = "INVENTORY_CREATED";
export const INVENTORY_UPDATED = "INVENTORY_UPDATED";
export const INVENTORY_DELETED = "INVENTORY_DELETED";