export const ORDER_CREATED = "ORDER_CREATED";
export const ORDER_UPDATED = "ORDER_UPDATED";
export const ORDER_CANCELLED = "ORDER_CANCELLED";

export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAILED = "PAYMENT_FAILED";

export const INVENTORY_UPDATED = "INVENTORY_UPDATED";
export const PAYMENT_INITIATED = "PAYMENT_INITIATED";
export const COD_PAYMENT_RECEIVED = "COD_Payment_Recieved";
export const PROCESS_REFUND = "PROCESS_REFUND";

export const ORDER_ITEM_CANCELLED = "ORDER_ITEM_CANCELLED";
