export const ORDER_CREATED = "ORDER_CREATED";
export const ORDER_UPDATED = "ORDER_UPDATED";
export const ORDER_CANCELLED = "ORDER_CANCELLED";

export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAILED = "PAYMENT_FAILED";
export const PAYMENT_PENDING = "PAYMENT_PENDING";
export const PAYMENT_REFUNDED = "PAYMENT_REFUNDED";
export const PAYMENT_INITIATED = "PAYMENT_INITIATED";

export const INVENTORY_UPDATED = "INVENTORY_UPDATED";
export const SELLER_ORDERS_CREATED = "SELLER_ORDERS_CREATED";
export const SHIPMENT_DELIVERED = "SHIPMENT_DELIVERED";

export const ORDER_CONFIRMED = "ORDER_CONFIRMED";
export const ORDER_PROCESSED = "ORDER_PROCESSED";
export const ORDER_SHIPPED = "ORDER_SHIPPED";
export const ORDER_OUT_FOR_DELIVERY = "ORDER_OUT_FOR_DELIVERY";
export const ORDER_DELIVERED = "ORDER_DELIVERED";
export const RETURN_REQUEST_APPROVED = "RETURN_REQUEST_APPROVED";

export const ORDER_ITEM_CANCELLED = "ORDER_ITEM_CANCELLED";
export const ORDER_ITEM_UPDATE = "ORDER_ITEM_UPDATE";

